development:
  db:
    uri: "mongodb://localhost/cphone_dev"
  facebook:
    appId: "280674075334047"
    appSecret: "62abcbf79fbdf7a018430d9ea6e09387"
    host_uri: "http://localhost:3001"
staging:
  db:
    uri: "mongodb://localhost/noobjs_stage"
  facebook:
    appId: "280674075334047"
    appSecret: "62abcbf79fbdf7a018430d9ea6e09387"
    host_uri: "http://localhost:3000"
production:
  db:
    uri: "mongodb://nodejs:nodejs@cp.mongohq.com:10045/app2591449"
  facebook:
    appId: "280674075334047"
    appSecret: "62abcbf79fbdf7a018430d9ea6e09387"
    host_uri: "http://nodejs-express-demo.herokuapp.com"
